### PR TITLE
fix link to API

### PR DESCRIPTION
**Pull request by bassdread**
fix https://github.com/urbanairship/python-library/issues/22

### CODE REVIEW

**Comment by bassdread** [comment]
Not sure if that is the right URL but it's not a 404

**Comment by robotadam** [comment]
Thanks! 

That'd work for the API, but we might use `http://docs.urbanairship.com/api/` instead, to get more of a landing page. We'll check with our docs team and see which they prefer.

**Comment by maxmarchuk** [comment]
The docs team prefers using `http://docs.urbanairship.com/api/`.
@bassdread if you could change it to that and sign our [CLA](http://urbanairship.com/legal/contribution-agreement) we'll merge the branch in. If you would prefer to not sign the CLA, we can take care of the URL change for you. Thank you!

**Comment by bassdread** [comment]
@maxmarchuk I won't sign the CLA. Just happy to help.

**Pull request closed without merging**
